name: dddapplication
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  bloc: ^8.1.1
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  google_sign_in: ^6.1.0
  get_it: ^7.5.0
  injectable: ^2.1.1
  flutter_bloc: ^8.1.2
  #flushbar: ^1.10.4
  uuid: ^3.0.7
  auto_route: ^7.1.0
  freezed_annotation: ^2.2.0
  cloud_firestore: ^4.7.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  freezed: ^2.3.2
  auto_route_generator: ^7.0.0
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/icon_notes.png
    - assets/images/app_icon.png
